services:
  avito-shop:
    build: .
    ports:
      - 8080:80
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: shop
      SERVER_PORT: 80
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d shop'" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s